apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
  namespace: dev
  annotations:
      circleci.com/project-id: abab4f4b-ee8c-40ad-b822-9f0fc49f66fe
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-k8s-app
        image: yannis411/my-k8s-app:latest
        ports:
        - containerPort: 3000